#include "TCanvas.h"
#include "TROOT.h"
#include "TF1.h"
#include "TLegend.h"
#include "TLatex.h"
//NO CUTS:
string ver = "y04";
void attach_y04() {
  double N1 = 748300; //HT 100 to 200
  double N2 = 1248911; //HT 200 to 400
  double N3 = 411531; //HT 400 to 600
  double N4 = 1560343; //HT 600 to 800
  double N5 = 737750; //HT 800 to 1200
  double N6 = 775061; //HT 1200 to 2500
  double N7 = 429253; //HT 2500 to Inf
  double N = 556249; // 200_195_10
  double XSEC1 = 1395*1.17*1000;
  double XSEC2 = 408.7*1.17*1000;
  double XSEC3 = 57.52*1.17*1000;
  double XSEC4 = 12.78*1.17*1000;
  double XSEC5 = 5.246*1.17*1000;
  double XSEC6 = 1.071*1.17*1000;
  double XSEC7 = 0.00819*1.17*1000;
  double XSECCH = 0.902569*1000;
  double L = 60;
  double SF1 = N1 / 29521158;
  double SF2 = N2 / 25468933;
  double SF3 = N3 / 5932701;
  double SF4 = N4 / 19771294;
  double SF5 = N5 / 8402687;
  double SF6 = N6 / 7633949;
  double SF7 = N7 / 3273980;
  double SFCH = 1;
  double BR = 1;//0.1063; //W -> muonic

  TFile *f1 = new TFile("y04_1.root");
  TFile *f2 = new TFile("y04_2.root");
  TFile *f3 = new TFile("y04_3.root");
  TFile *f4 = new TFile("y04_4.root");
  TFile *f5 = new TFile("y04_5.root");
  TFile *f6 = new TFile("y04_6.root");
  TFile *f7 = new TFile("y04_7.root");
  TFile *fch = new TFile("y04.root");

  TH1F *met1 = (TH1F*)f1->Get("plots/metpt");
  TH1F *met2 = (TH1F*)f2->Get("plots/metpt");
  TH1F *met3 = (TH1F*)f3->Get("plots/metpt");
  TH1F *met4 = (TH1F*)f4->Get("plots/metpt");
  TH1F *met5 = (TH1F*)f5->Get("plots/metpt");
  TH1F *met6 = (TH1F*)f6->Get("plots/metpt");
  TH1F *met7 = (TH1F*)f7->Get("plots/metpt");
  TH1F *met8 = (TH1F*)f8->Get("plots/metpt");
  TH1F *met9 = (TH1F*)f9->Get("plots/metpt");
  TH1F *met10 = (TH1F*)f10->Get("plots/metpt");
  TH1F *metch = (TH1F*)fch->Get("plots/metpt");
  TH1F *metbg = new TH1F("bg_met", "\\mbox{Missing Energy Transverse MET (Total Background)}", 90, 0, 700);
  TH1F *metbg_w = new TH1F("bg_met_w", "\\mbox{Missing Energy Transverse MET (WJets Background)}", 90, 0, 700);
  TH1F *metbg_tt = new TH1F("bg_met_tt", "\\mbox{Missing Energy Transverse MET (TTJets Background)}", 90, 0, 700);


  TH1F *hn1 = (TH1F*)f1->Get("plots/N");
  TH1F *hn2 = (TH1F*)f2->Get("plots/N");
  TH1F *hn3 = (TH1F*)f3->Get("plots/N");
  TH1F *hn4 = (TH1F*)f4->Get("plots/N");
  TH1F *hn5 = (TH1F*)f5->Get("plots/N");
  TH1F *hn6 = (TH1F*)f6->Get("plots/N");
  TH1F *hn7 = (TH1F*)f7->Get("plots/N");
  TH1F *hn8 = (TH1F*)f8->Get("plots/N");
  TH1F *hn9 = (TH1F*)f9->Get("plots/N");
  TH1F *hn10 = (TH1F*)f10->Get("plots/N");
  TH1F *hnch = (TH1F*)fch->Get("plots/N");
  TH1F *hnbg = new TH1F("bg_N", "\\mbox{Number of Events (background)}", 1, 0, 1);
  TH1F *hnbg_w = new TH1F("bg_Nw", "\\mbox{Number of Events (background)}", 1, 0, 1);
  TH1F *hnbg_tt = new TH1F("bg_Ntt", "\\mbox{Number of Events (background)}", 1, 0, 1);

  double hn1_entries = hn1->GetEntries()*1/N1*XSEC1*L*SF1*BR;
  double hn2_entries = hn2->GetEntries()*1/N2*XSEC2*L*SF2*BR;
  double hn3_entries = hn3->GetEntries()*1/N3*XSEC3*L*SF3*BR;
  double hn4_entries = hn4->GetEntries()*1/N4*XSEC4*L*SF4*BR;
  double hn5_entries = hn5->GetEntries()*1/N5*XSEC5*L*SF5*BR;
  double hn6_entries = hn6->GetEntries()*1/N6*XSEC6*L*SF6*BR;
  double hn7_entries = hn7->GetEntries()*1/N7*XSEC7*L*SF7*BR;
  double hn8_entries = hn8->GetEntries()*1/N8*XSEC8*L*SF8*BR;
  double hn9_entries = hn9->GetEntries()*1/N9*XSEC9*L*SF9*BR;
  double hn10_entries = hn10->GetEntries()*1/N10*XSEC10*L*SF10*BR;
  double hnch_entries = hnch->GetEntries()*1/N*XSECCH*L*SFCH*BR;
  double hnbg_entries = 0;
  double hnbg_w_entries = 0;
  double hnbg_tt_entries = 0;

  TH1F *mu1 = (TH1F*)f1->Get("plots/mupt");
  TH1F *mu2 = (TH1F*)f2->Get("plots/mupt");
  TH1F *mu3 = (TH1F*)f3->Get("plots/mupt");
  TH1F *mu4 = (TH1F*)f4->Get("plots/mupt");
  TH1F *mu5 = (TH1F*)f5->Get("plots/mupt");
  TH1F *mu6 = (TH1F*)f6->Get("plots/mupt");
  TH1F *mu7 = (TH1F*)f7->Get("plots/mupt");
  TH1F *mu8 = (TH1F*)f8->Get("plots/mupt");
  TH1F *mu9 = (TH1F*)f9->Get("plots/mupt");
  TH1F *mu10 = (TH1F*)f10->Get("plots/mupt");
  TH1F *much = (TH1F*)fch->Get("plots/mupt");
  TH1F *mubg = new TH1F("bg_mupt", "\\mbox{Muon Transverse Momentum (Total Background) }p_t", 90, 0, 75);
  TH1F *mubg_w = new TH1F("bg_mupt_w", "\\mbox{Muon Transverse Momentum (WJets Background) }p_t", 90, 0, 75);
  TH1F *mubg_tt = new TH1F("bg_mupt_tt", "\\mbox{Muon Transverse Momentum (TTJets Background) }p_t", 90, 0, 75);


  TH1F *eta1 = (TH1F*)f1->Get("plots/mueta");
  TH1F *eta2 = (TH1F*)f2->Get("plots/mueta");
  TH1F *eta3 = (TH1F*)f3->Get("plots/mueta");
  TH1F *eta4 = (TH1F*)f4->Get("plots/mueta");
  TH1F *eta5 = (TH1F*)f5->Get("plots/mueta");
  TH1F *eta6 = (TH1F*)f6->Get("plots/mueta");
  TH1F *eta7 = (TH1F*)f7->Get("plots/mueta");
  TH1F *eta8 = (TH1F*)f8->Get("plots/mueta");
  TH1F *eta9 = (TH1F*)f9->Get("plots/mueta");
  TH1F *eta10 = (TH1F*)f10->Get("plots/mueta");
  TH1F *etach = (TH1F*)fch->Get("plots/mueta");
  TH1F *etabg = new TH1F("bg_mueta", "\\mbox{Muon Pseudorapidity (Total Background) } \\eta", 90, -2.5, 2.5);
  TH1F *etabg_w = new TH1F("bg_mueta_w", "\\mbox{Muon Pseudorapidity (WJets Background) } \\eta", 90, -2.5, 2.5);
  TH1F *etabg_tt = new TH1F("bg_mueta_tt", "\\mbox{Muon Pseudorapidity (TTJets Background) } \\eta", 90, -2.5, 2.5);


  TH1F *h1_1 = (TH1F*)f1->Get("plots/jetht1");
  TH1F *h2_1 = (TH1F*)f2->Get("plots/jetht1");
  TH1F *h3_1 = (TH1F*)f3->Get("plots/jetht1");
  TH1F *h4_1 = (TH1F*)f4->Get("plots/jetht1");
  TH1F *h5_1 = (TH1F*)f5->Get("plots/jetht1");
  TH1F *h6_1 = (TH1F*)f6->Get("plots/jetht1");
  TH1F *h7_1 = (TH1F*)f7->Get("plots/jetht1");
  TH1F *h8_1 = (TH1F*)f8->Get("plots/jetht1");
  TH1F *h9_1 = (TH1F*)f9->Get("plots/jetht1");
  TH1F *h10_1 = (TH1F*)f10->Get("plots/jetht1");
  TH1F *hch_1 = (TH1F*)fch->Get("plots/jetht1");
  TH1F *hbg_1 = new TH1F("bg_jetht1", "\\mbox{Total Jet HT (background) for length cut } d_1", 100, 0, 3600);
  TH1F *htotal_1 = new TH1F("total_jetht1", "\\mbox{Total Jet HT (plus chargino) for length cut } d_1", 100, 0, 3600);

  TH1F *h1_2 = (TH1F*)f1->Get("plots/jetht2");
  TH1F *h2_2 = (TH1F*)f2->Get("plots/jetht2");
  TH1F *h3_2 = (TH1F*)f3->Get("plots/jetht2");
  TH1F *h4_2 = (TH1F*)f4->Get("plots/jetht2");
  TH1F *h5_2 = (TH1F*)f5->Get("plots/jetht2");
  TH1F *h6_2 = (TH1F*)f6->Get("plots/jetht2");
  TH1F *h7_2 = (TH1F*)f7->Get("plots/jetht2");
  TH1F *h8_2 = (TH1F*)f8->Get("plots/jetht2");
  TH1F *h9_2 = (TH1F*)f9->Get("plots/jetht2");
  TH1F *h10_2 = (TH1F*)f10->Get("plots/jetht2");
  TH1F *hch_2 = (TH1F*)fch->Get("plots/jetht2");
  TH1F *hbg_2 = new TH1F("bg_jetht2", "\\mbox{Total Jet HT (background) for length cut } d_2", 100, 0, 3600);
  TH1F *htotal_2 = new TH1F("total_jetht2", "\\mbox{Total Jet HT (plus chargino) for length cut } d_2", 100, 0, 3600);

  TH1F *h1_3 = (TH1F*)f1->Get("plots/jetht3");
  TH1F *h2_3 = (TH1F*)f2->Get("plots/jetht3");
  TH1F *h3_3 = (TH1F*)f3->Get("plots/jetht3");
  TH1F *h4_3 = (TH1F*)f4->Get("plots/jetht3");
  TH1F *h5_3 = (TH1F*)f5->Get("plots/jetht3");
  TH1F *h6_3 = (TH1F*)f6->Get("plots/jetht3");
  TH1F *h7_3 = (TH1F*)f7->Get("plots/jetht3");
  TH1F *h8_3 = (TH1F*)f8->Get("plots/jetht3");
  TH1F *h9_3 = (TH1F*)f9->Get("plots/jetht3");
  TH1F *h10_3 = (TH1F*)f10->Get("plots/jetht3");
  TH1F *hch_3 = (TH1F*)fch->Get("plots/jetht3");
  TH1F *hbg_3 = new TH1F("bg_jetht3", "\\mbox{Total Jet HT (background) for length cut } d_3", 100, 0, 3600);
  TH1F *htotal_3 = new TH1F("total_jetht3", "\\mbox{Total Jet HT (plus chargino) for length cut } d_3", 100, 0, 3600);

  TH1F *h1_4 = (TH1F*)f1->Get("plots/jetht4");
  TH1F *h2_4 = (TH1F*)f2->Get("plots/jetht4");
  TH1F *h3_4 = (TH1F*)f3->Get("plots/jetht4");
  TH1F *h4_4 = (TH1F*)f4->Get("plots/jetht4");
  TH1F *h5_4 = (TH1F*)f5->Get("plots/jetht4");
  TH1F *h6_4 = (TH1F*)f6->Get("plots/jetht4");
  TH1F *h7_4 = (TH1F*)f7->Get("plots/jetht4");
  TH1F *h8_4 = (TH1F*)f8->Get("plots/jetht4");
  TH1F *h9_4 = (TH1F*)f9->Get("plots/jetht4");
  TH1F *h10_4 = (TH1F*)f10->Get("plots/jetht4");
  TH1F *hch_4 = (TH1F*)fch->Get("plots/jetht4");
  TH1F *hbg_4 = new TH1F("bg_jetht4", "\\mbox{Total Jet HT (background) for length cut } d_4", 100, 0, 3600);
  TH1F *htotal_4 = new TH1F("total_jetht4", "\\mbox{Total Jet HT (plus chargino) for length cut } d_4", 100, 0, 3600);

  TH1F *h1_5 = (TH1F*)f1->Get("plots/jetht5");
  TH1F *h2_5 = (TH1F*)f2->Get("plots/jetht5");
  TH1F *h3_5 = (TH1F*)f3->Get("plots/jetht5");
  TH1F *h4_5 = (TH1F*)f4->Get("plots/jetht5");
  TH1F *h5_5 = (TH1F*)f5->Get("plots/jetht5");
  TH1F *h6_5 = (TH1F*)f6->Get("plots/jetht5");
  TH1F *h7_5 = (TH1F*)f7->Get("plots/jetht5");
  TH1F *h8_5 = (TH1F*)f8->Get("plots/jetht5");
  TH1F *h9_5 = (TH1F*)f9->Get("plots/jetht5");
  TH1F *h10_5 = (TH1F*)f10->Get("plots/jetht5");
  TH1F *hch_5 = (TH1F*)fch->Get("plots/jetht5");
  TH1F *hbg_5 = new TH1F("bg_jetht5", "\\mbox{Total Jet HT (background) for length cut } d_5", 100, 0, 3600);
  TH1F *htotal_5 = new TH1F("total_jetht5", "\\mbox{Total Jet HT (plus chargino) for length cut } d_5", 100, 0, 3600);

  met1->Scale(1/N1*XSEC1*L*SF1*BR);
  met2->Scale(1/N2*XSEC2*L*SF2*BR);
  met3->Scale(1/N3*XSEC3*L*SF3*BR);
  met4->Scale(1/N4*XSEC4*L*SF4*BR);
  met5->Scale(1/N5*XSEC5*L*SF5*BR);
  met6->Scale(1/N6*XSEC6*L*SF6*BR);
  met7->Scale(1/N7*XSEC7*L*SF7*BR);
  met8->Scale(1/N8*XSEC8*L*SF8*BR);
  met9->Scale(1/N9*XSEC9*L*SF9*BR);
  met10->Scale(1/N10*XSEC10*L*SF10*BR);
  metch->Scale(1/N*XSECCH*L*SFCH*BR);

  hn1->Scale(1/N1*XSEC1*L*SF1*BR);
  hn2->Scale(1/N2*XSEC2*L*SF2*BR);
  hn3->Scale(1/N3*XSEC3*L*SF3*BR);
  hn4->Scale(1/N4*XSEC4*L*SF4*BR);
  hn5->Scale(1/N5*XSEC5*L*SF5*BR);
  hn6->Scale(1/N6*XSEC6*L*SF6*BR);
  hn7->Scale(1/N7*XSEC7*L*SF7*BR);
  hn8->Scale(1/N8*XSEC8*L*SF8*BR);
  hn9->Scale(1/N9*XSEC9*L*SF9*BR);
  hn10->Scale(1/N10*XSEC10*L*SF10*BR);
  hnch->Scale(1/N*XSECCH*L*SFCH*BR);

  mu1->Scale(1/N1*XSEC1*L*SF1*BR);
  mu2->Scale(1/N2*XSEC2*L*SF2*BR);
  mu3->Scale(1/N3*XSEC3*L*SF3*BR);
  mu4->Scale(1/N4*XSEC4*L*SF4*BR);
  mu5->Scale(1/N5*XSEC5*L*SF5*BR);
  mu6->Scale(1/N6*XSEC6*L*SF6*BR);
  mu7->Scale(1/N7*XSEC7*L*SF7*BR);
  mu8->Scale(1/N8*XSEC8*L*SF8*BR);
  mu9->Scale(1/N9*XSEC9*L*SF9*BR);
  mu10->Scale(1/N10*XSEC10*L*SF10*BR);
  much->Scale(1/N*XSECCH*L*SFCH*BR);

  eta1->Scale(1/N1*XSEC1*L*SF1*BR);
  eta2->Scale(1/N2*XSEC2*L*SF2*BR);
  eta3->Scale(1/N3*XSEC3*L*SF3*BR);
  eta4->Scale(1/N4*XSEC4*L*SF4*BR);
  eta5->Scale(1/N5*XSEC5*L*SF5*BR);
  eta6->Scale(1/N6*XSEC6*L*SF6*BR);
  eta7->Scale(1/N7*XSEC7*L*SF7*BR);
  eta8->Scale(1/N8*XSEC8*L*SF8*BR);
  eta9->Scale(1/N9*XSEC9*L*SF9*BR);
  eta10->Scale(1/N10*XSEC10*L*SF10*BR);
  etach->Scale(1/N*XSECCH*L*SFCH*BR);

  h1_1->Scale(1/N1*XSEC1*L*SF1*BR);
  h2_1->Scale(1/N2*XSEC2*L*SF2*BR);
  h3_1->Scale(1/N3*XSEC3*L*SF3*BR);
  h4_1->Scale(1/N4*XSEC4*L*SF4*BR);
  h5_1->Scale(1/N5*XSEC5*L*SF5*BR);
  h6_1->Scale(1/N6*XSEC6*L*SF6*BR);
  h7_1->Scale(1/N7*XSEC7*L*SF7*BR);
  h8_1->Scale(1/N8*XSEC8*L*SF8*BR);
  h9_1->Scale(1/N9*XSEC9*L*SF9*BR);
  h10_1->Scale(1/N10*XSEC10*L*SF10*BR);
  hch_1->Scale(1/N*XSECCH*L*SFCH*BR);

  h1_2->Scale(1/N1*XSEC1*L*SF1*BR);
  h2_2->Scale(1/N2*XSEC2*L*SF2*BR);
  h3_2->Scale(1/N3*XSEC3*L*SF3*BR);
  h4_2->Scale(1/N4*XSEC4*L*SF4*BR);
  h5_2->Scale(1/N5*XSEC5*L*SF5*BR);
  h6_2->Scale(1/N6*XSEC6*L*SF6*BR);
  h7_2->Scale(1/N7*XSEC7*L*SF7*BR);
  h8_2->Scale(1/N8*XSEC8*L*SF8*BR);
  h9_2->Scale(1/N9*XSEC9*L*SF9*BR);
  h10_2->Scale(1/N10*XSEC10*L*SF10*BR);
  hch_2->Scale(1/N*XSECCH*L*SFCH*BR);

  h1_3->Scale(1/N1*XSEC1*L*SF1*BR);
  h2_3->Scale(1/N2*XSEC2*L*SF2*BR);
  h3_3->Scale(1/N3*XSEC3*L*SF3*BR);
  h4_3->Scale(1/N4*XSEC4*L*SF4*BR);
  h5_3->Scale(1/N5*XSEC5*L*SF5*BR);
  h6_3->Scale(1/N6*XSEC6*L*SF6*BR);
  h7_3->Scale(1/N7*XSEC7*L*SF7*BR);
  h8_3->Scale(1/N8*XSEC8*L*SF8*BR);
  h9_3->Scale(1/N9*XSEC9*L*SF9*BR);
  h10_3->Scale(1/N10*XSEC10*L*SF10*BR);
  hch_3->Scale(1/N*XSECCH*L*SFCH*BR);

  h1_4->Scale(1/N1*XSEC1*L*SF1*BR);
  h2_4->Scale(1/N2*XSEC2*L*SF2*BR);
  h3_4->Scale(1/N3*XSEC3*L*SF3*BR);
  h4_4->Scale(1/N4*XSEC4*L*SF4*BR);
  h5_4->Scale(1/N5*XSEC5*L*SF5*BR);
  h6_4->Scale(1/N6*XSEC6*L*SF6*BR);
  h7_4->Scale(1/N7*XSEC7*L*SF7*BR);
  h8_4->Scale(1/N8*XSEC8*L*SF8*BR);
  h9_4->Scale(1/N9*XSEC9*L*SF9*BR);
  h10_4->Scale(1/N10*XSEC10*L*SF10*BR);
  hch_4->Scale(1/N*XSECCH*L*SFCH*BR);

  h1_5->Scale(1/N1*XSEC1*L*SF1*BR);
  h2_5->Scale(1/N2*XSEC2*L*SF2*BR);
  h3_5->Scale(1/N3*XSEC3*L*SF3*BR);
  h4_5->Scale(1/N4*XSEC4*L*SF4*BR);
  h5_5->Scale(1/N5*XSEC5*L*SF5*BR);
  h6_5->Scale(1/N6*XSEC6*L*SF6*BR);
  h7_5->Scale(1/N7*XSEC7*L*SF7*BR);
  h8_5->Scale(1/N8*XSEC8*L*SF8*BR);
  h9_5->Scale(1/N9*XSEC9*L*SF9*BR);
  h10_5->Scale(1/N10*XSEC10*L*SF10*BR);
  hch_5->Scale(1/N*XSECCH*L*SFCH*BR);

  metbg->Add(met1);
  metbg->Add(met2);
  metbg->Add(met3);
  metbg->Add(met4);
  metbg->Add(met5);
  metbg->Add(met6);
  metbg->Add(met7);
  metbg->Add(met8);
  metbg->Add(met9);
  metbg->Add(met10);
  metbg_w->Add(met1);
  metbg_w->Add(met2);
  metbg_w->Add(met3);
  metbg_w->Add(met4);
  metbg_w->Add(met5);
  metbg_w->Add(met6);
  metbg_w->Add(met7);
  metbg_tt->Add(met8);
  metbg_tt->Add(met9);
  metbg_tt->Add(met10);

  hnbg->Add(hn1);
  hnbg->Add(hn2);
  hnbg->Add(hn3);
  hnbg->Add(hn4);
  hnbg->Add(hn5);
  hnbg->Add(hn6);
  hnbg->Add(hn7);
  hnbg->Add(hn8);
  hnbg->Add(hn9);
  hnbg->Add(hn10);

  hnbg_w->Add(hn1);
  hnbg_w->Add(hn2);
  hnbg_w->Add(hn3);
  hnbg_w->Add(hn4);
  hnbg_w->Add(hn5);
  hnbg_w->Add(hn6);
  hnbg_w->Add(hn7);
  hnbg_tt->Add(hn8);
  hnbg_tt->Add(hn9);
  hnbg_tt->Add(hn10);

  hnbg_entries += hn1_entries;
  hnbg_entries += hn2_entries;
  hnbg_entries += hn3_entries;
  hnbg_entries += hn4_entries;
  hnbg_entries += hn5_entries;
  hnbg_entries += hn6_entries;
  hnbg_entries += hn7_entries;
  hnbg_entries += hn8_entries;
  hnbg_entries += hn9_entries;
  hnbg_entries += hn10_entries;
  hnbg_w_entries += hn1_entries;
  hnbg_w_entries += hn2_entries;
  hnbg_w_entries += hn3_entries;
  hnbg_w_entries += hn4_entries;
  hnbg_w_entries += hn5_entries;
  hnbg_w_entries += hn6_entries;
  hnbg_w_entries += hn7_entries;
  hnbg_tt_entries += hn8_entries;
  hnbg_tt_entries += hn9_entries;
  hnbg_tt_entries += hn10_entries;

  mubg->Add(mu1);
  mubg->Add(mu2);
  mubg->Add(mu3);
  mubg->Add(mu4);
  mubg->Add(mu5);
  mubg->Add(mu6);
  mubg->Add(mu7);
  mubg->Add(mu8);
  mubg->Add(mu9);
  mubg_w->Add(mu1);
  mubg_w->Add(mu2);
  mubg_w->Add(mu3);
  mubg_w->Add(mu4);
  mubg_w->Add(mu5);
  mubg_w->Add(mu6);
  mubg_w->Add(mu7);
  mubg_tt->Add(mu8);
  mubg_tt->Add(mu9);
  mubg_tt->Add(mu10);

  etabg->Add(eta1);
  etabg->Add(eta2);
  etabg->Add(eta3);
  etabg->Add(eta4);
  etabg->Add(eta5);
  etabg->Add(eta6);
  etabg->Add(eta7);
  etabg->Add(eta8);
  etabg->Add(eta9);
  etabg->Add(eta10);
  etabg_w->Add(eta1);
  etabg_w->Add(eta2);
  etabg_w->Add(eta3);
  etabg_w->Add(eta4);
  etabg_w->Add(eta5);
  etabg_w->Add(eta6);
  etabg_w->Add(eta7);
  etabg_tt->Add(eta8);
  etabg_tt->Add(eta9);
  etabg_tt->Add(eta10);

  hbg_1->Add(h1_1);
  hbg_1->Add(h2_1);
  hbg_1->Add(h3_1);
  hbg_1->Add(h4_1);
  hbg_1->Add(h5_1);
  hbg_1->Add(h6_1);
  hbg_1->Add(h7_1);
  hbg_1->Add(h8_1);
  hbg_1->Add(h9_1);
  hbg_1->Add(h10_1);
  htotal_1->Add(hbg_1);
  htotal_1->Add(hch_1);

  hbg_2->Add(h1_2);
  hbg_2->Add(h2_2);
  hbg_2->Add(h3_2);
  hbg_2->Add(h4_2);
  hbg_2->Add(h5_2);
  hbg_2->Add(h6_2);
  hbg_2->Add(h7_2);
  hbg_2->Add(h8_2);
  hbg_2->Add(h9_2);
  hbg_2->Add(h10_2);
  htotal_2->Add(hbg_2);
  htotal_2->Add(hch_2);

  hbg_3->Add(h1_3);
  hbg_3->Add(h2_3);
  hbg_3->Add(h3_3);
  hbg_3->Add(h4_3);
  hbg_3->Add(h5_3);
  hbg_3->Add(h6_3);
  hbg_3->Add(h7_3);
  hbg_3->Add(h8_3);
  hbg_3->Add(h9_3);
  hbg_3->Add(h10_3);
  htotal_3->Add(hbg_3);
  htotal_3->Add(hch_3);

  hbg_4->Add(h1_4);
  hbg_4->Add(h2_4);
  hbg_4->Add(h3_4);
  hbg_4->Add(h4_4);
  hbg_4->Add(h5_4);
  hbg_4->Add(h6_4);
  hbg_4->Add(h7_4);
  hbg_4->Add(h8_4);
  hbg_4->Add(h9_4);
  hbg_4->Add(h10_4);
  htotal_4->Add(hbg_4);
  htotal_4->Add(hch_4);

  hbg_5->Add(h1_5);
  hbg_5->Add(h2_5);
  hbg_5->Add(h3_5);
  hbg_5->Add(h4_5);
  hbg_5->Add(h5_5);
  hbg_5->Add(h6_5);
  hbg_5->Add(h7_5);
  hbg_5->Add(h8_5);
  hbg_5->Add(h9_5);
  hbg_5->Add(h10_5);
  htotal_5->Add(hbg_5);
  htotal_5->Add(hch_5);

  double hbg_1_area = hbg_1->Integral();
  double hbg_2_area = hbg_2->Integral();
  double hbg_3_area = hbg_3->Integral();
  double hbg_4_area = hbg_4->Integral();
  double hbg_5_area = hbg_5->Integral();
  double hch_1_area = hch_1->Integral();
  double hch_2_area = hch_2->Integral();
  double hch_3_area = hch_3->Integral();
  double hch_4_area = hch_4->Integral();
  double hch_5_area = hch_5->Integral();
  double htotal_1_area = htotal_1->Integral();
  double htotal_2_area = htotal_2->Integral();
  double htotal_3_area = htotal_3->Integral();
  double htotal_4_area = htotal_4->Integral();
  double htotal_5_area = htotal_5->Integral();
  double metbg_area = metbg->Integral();
  double metch_area = metch->Integral();
  double mubg_area = mubg->Integral();
  double hnbg_area = hnbg->Integral();
  double hnbg_w_area = hnbg->Integral();
  double hnbg_tt_area = hnbg->Integral();
  double hnch_area = hnch->Integral();

  cout << "MET integral background = " << metbg_area << endl;
  cout << "Muon pt integral background = " << mubg_area << endl;
  cout << "HT integral background (d1) = " << hbg_1_area << endl;
  cout << "HT integral background (d2) = " << hbg_2_area << endl;
  cout << "HT integral background (d3) = " << hbg_3_area << endl;
  cout << "HT integral background (d4) = " << hbg_4_area << endl;
  cout << "HT integral background (d5) = " << hbg_5_area << endl;
  cout << "MET integral chargino only = " << metch_area << endl;
  cout << "HT integral chargino only (d1) = " << hch_1_area << endl;
  cout << "HT integral chargino only (d2) = " << hch_2_area << endl;
  cout << "HT integral chargino only (d3) = " << hch_3_area << endl;
  cout << "HT integral chargino only (d4) = " << hch_4_area << endl;
  cout << "HT integral chargino only (d5) = " << hch_5_area << endl;
  cout << "HT integral total (d1) = " << htotal_1_area << endl;
  cout << "HT integral total (d2) = " << htotal_2_area << endl;
  cout << "HT integral total (d3) = " << htotal_3_area << endl;
  cout << "HT integral total (d4) = " << htotal_4_area << endl;
  cout << "HT integral total (d5) = " << htotal_5_area << endl;
  cout << "Chargino Signal event / Total Signal event ratio (d1), % = " << hch_1_area / htotal_1_area * 100 << endl;
  cout << "Chargino Signal event / Total Signal event ratio (d2), % = " << hch_2_area / htotal_2_area * 100 << endl;
  cout << "Chargino Signal event / Total Signal event ratio (d3), % = " << hch_3_area / htotal_3_area * 100 << endl;
  cout << "Chargino Signal event / Total Signal event ratio (d4), % = " << hch_4_area / htotal_4_area * 100 << endl;
  cout << "Chargino Signal event / Total Signal event ratio (d5), % = " << hch_5_area / htotal_5_area * 100 << endl;
  cout << "-----" << endl;
  cout << "Chargino Physical Events (best accuracy) = " << hnch_entries << endl;
  cout << "Background Total Physical Events (best accuracy) = " << hnbg_entries<< endl;
  cout << "Background WJets Physical Events (best accuracy) = " << hnbg_w_entries << endl;
  cout << "Background TTJets Physical Events (best accuracy) = " << hnbg_tt_entries << endl;

  TCanvas* c = new TCanvas("canv_y04", "The Canvas (post-analysis)", 1000, 700);
  gStyle->SetOptStat(1110);
  gStyle->SetStatColor(18);
  //metch->SetLineColor(38);
  //metch->GetXaxis()->SetTitle("\\mbox{MET (GeV)}");
  //metch->GetXaxis()->CenterTitle(true);
  //metch->GetYaxis()->SetTitle("Counts");
  //metch->GetYaxis()->CenterTitle(true);
  metbg->SetLineColor(38);
  metbg->GetXaxis()->SetTitle("\\mbox{MET (GeV)}");
  metbg->GetXaxis()->CenterTitle(true);
  metbg->GetYaxis()->SetTitle("Counts");
  metbg->GetYaxis()->CenterTitle(true);
  metbg_w->SetLineColor(38);
  metbg_w->GetXaxis()->SetTitle("\\mbox{MET (GeV)}");
  metbg_w->GetXaxis()->CenterTitle(true);
  metbg_w->GetYaxis()->SetTitle("Counts");
  metbg_w->GetYaxis()->CenterTitle(true);
  metbg_tt->SetLineColor(38);
  metbg_tt->GetXaxis()->SetTitle("\\mbox{MET (GeV)}");
  metbg_tt->GetXaxis()->CenterTitle(true);
  metbg_tt->GetYaxis()->SetTitle("Counts");
  metbg_tt->GetYaxis()->CenterTitle(true);
  mubg->SetLineColor(38);
  mubg->GetXaxis()->SetTitle("\\mbox{p_t (GeV)}");
  mubg->GetXaxis()->CenterTitle(true);
  mubg->GetYaxis()->SetTitle("Counts");
  mubg->GetYaxis()->CenterTitle(true);
  mubg_w->SetLineColor(38);
  mubg_w->GetXaxis()->SetTitle("\\mbox{p_t (GeV)}");
  mubg_w->GetXaxis()->CenterTitle(true);
  mubg_w->GetYaxis()->SetTitle("Counts");
  mubg_w->GetYaxis()->CenterTitle(true);
  mubg_tt->SetLineColor(38);
  mubg_tt->GetXaxis()->SetTitle("\\mbox{p_t (GeV)}");
  mubg_tt->GetXaxis()->CenterTitle(true);
  mubg_tt->GetYaxis()->SetTitle("Counts");
  mubg_tt->GetYaxis()->CenterTitle(true);
  etabg->SetLineColor(38);
  etabg->GetXaxis()->SetTitle("\\eta");
  etabg->GetXaxis()->CenterTitle(true);
  etabg->GetYaxis()->SetTitle("Counts");
  etabg->GetYaxis()->CenterTitle(true);
  etabg_w->SetLineColor(38);
  etabg_w->GetXaxis()->SetTitle("\\eta");
  etabg_w->GetXaxis()->CenterTitle(true);
  etabg_w->GetYaxis()->SetTitle("Counts");
  etabg_w->GetYaxis()->CenterTitle(true);
  etabg_tt->SetLineColor(38);
  etabg_tt->GetXaxis()->SetTitle("\\eta");
  etabg_tt->GetXaxis()->CenterTitle(true);
  etabg_tt->GetYaxis()->SetTitle("Counts");
  etabg_tt->GetYaxis()->CenterTitle(true);
  hbg_1->SetLineColor(38);
  hbg_1->GetXaxis()->SetTitle("\\mbox{HT (GeV)}");
  hbg_1->GetXaxis()->CenterTitle(true);
  hbg_1->GetYaxis()->SetTitle("Counts");
  hbg_1->GetYaxis()->CenterTitle(true);
  hbg_2->SetLineColor(38);
  hbg_2->GetXaxis()->SetTitle("\\mbox{HT (GeV)}");
  hbg_2->GetXaxis()->CenterTitle(true);
  hbg_2->GetYaxis()->SetTitle("Counts");
  hbg_2->GetYaxis()->CenterTitle(true);
  hbg_3->SetLineColor(38);
  hbg_3->GetXaxis()->SetTitle("\\mbox{HT (GeV)}");
  hbg_3->GetXaxis()->CenterTitle(true);
  hbg_3->GetYaxis()->SetTitle("Counts");
  hbg_3->GetYaxis()->CenterTitle(true);
  hbg_4->SetLineColor(38);
  hbg_4->GetXaxis()->SetTitle("\\mbox{HT (GeV)}");
  hbg_4->GetXaxis()->CenterTitle(true);
  hbg_4->GetYaxis()->SetTitle("Counts");
  hbg_4->GetYaxis()->CenterTitle(true);
  hbg_5->SetLineColor(38);
  hbg_5->GetXaxis()->SetTitle("\\mbox{HT (GeV)}");
  hbg_5->GetXaxis()->CenterTitle(true);
  hbg_5->GetYaxis()->SetTitle("Counts");
  hbg_5->GetYaxis()->CenterTitle(true);
  hch_1->SetLineColor(38);
  hch_1->GetXaxis()->SetTitle("\\mbox{HT (GeV)}");
  hch_1->GetXaxis()->CenterTitle(true);
  hch_1->GetYaxis()->SetTitle("Counts");
  hch_1->GetYaxis()->CenterTitle(true);
  hch_2->SetLineColor(38);
  hch_2->GetXaxis()->SetTitle("\\mbox{HT (GeV)}");
  hch_2->GetXaxis()->CenterTitle(true);
  hch_2->GetYaxis()->SetTitle("Counts");
  hch_2->GetYaxis()->CenterTitle(true);
  hch_3->SetLineColor(38);
  hch_3->GetXaxis()->SetTitle("\\mbox{HT (GeV)}");
  hch_3->GetXaxis()->CenterTitle(true);
  hch_3->GetYaxis()->SetTitle("Counts");
  hch_3->GetYaxis()->CenterTitle(true);
  hch_4->SetLineColor(38);
  hch_4->GetXaxis()->SetTitle("\\mbox{HT (GeV)}");
  hch_4->GetXaxis()->CenterTitle(true);
  hch_4->GetYaxis()->SetTitle("Counts");
  hch_4->GetYaxis()->CenterTitle(true);
  hch_5->SetLineColor(38);
  hch_5->GetXaxis()->SetTitle("\\mbox{HT (GeV)}");
  hch_5->GetXaxis()->CenterTitle(true);
  hch_5->GetYaxis()->SetTitle("Counts");
  hch_5->GetYaxis()->CenterTitle(true);
  htotal_1->SetLineColor(38);
  htotal_1->GetXaxis()->SetTitle("\\mbox{HT (GeV)}");
  htotal_1->GetXaxis()->CenterTitle(true);
  htotal_1->GetYaxis()->SetTitle("Counts");
  htotal_1->GetYaxis()->CenterTitle(true);
  htotal_1->SetLineColor(38);
  htotal_2->GetXaxis()->SetTitle("\\mbox{HT (GeV)}");
  htotal_2->GetXaxis()->CenterTitle(true);
  htotal_2->GetYaxis()->SetTitle("Counts");
  htotal_2->GetYaxis()->CenterTitle(true);
  htotal_3->SetLineColor(38);
  htotal_3->GetXaxis()->SetTitle("\\mbox{HT (GeV)}");
  htotal_3->GetXaxis()->CenterTitle(true);
  htotal_3->GetYaxis()->SetTitle("Counts");
  htotal_3->GetYaxis()->CenterTitle(true);
  htotal_4->SetLineColor(38);
  htotal_4->GetXaxis()->SetTitle("\\mbox{HT (GeV)}");
  htotal_4->GetXaxis()->CenterTitle(true);
  htotal_4->GetYaxis()->SetTitle("Counts");
  htotal_4->GetYaxis()->CenterTitle(true);
  htotal_5->SetLineColor(38);
  htotal_5->GetXaxis()->SetTitle("\\mbox{HT (GeV)}");
  htotal_5->GetXaxis()->CenterTitle(true);
  htotal_5->GetYaxis()->SetTitle("Counts");
  htotal_5->GetYaxis()->CenterTitle(true);
  metch->Draw("HIST");
  c->SaveAs("sattach_y04_ch_met.png");
  metbg->Draw("HIST");
  c->SaveAs("sattach_y04_bg_met.png");
  metbg_w->Draw("HIST");
  c->SaveAs("sattach_y04_bg_w_met.png");
  metbg_tt->Draw("HIST");
  c->SaveAs("sattach_y04_bg_tt_met.png");
  much->Draw("HIST");
  c->SaveAs("sattach_y04_ch_mupt.png");
  mubg->SetLineColor(kCyan+3);
  mubg->SetFillColor(kCyan+3);
  mubg->SetLineWidth(2);
  mubg->GetXaxis()->CenterTitle(true);
  mubg->GetYaxis()->CenterTitle(true);
  mubg->Draw("HIST");
  c->SaveAs("sattach_y04_bg_mupt.png");
  mubg_w->SetLineColor(kCyan+2);
  mubg_w->SetFillColor(kCyan+2);
  mubg_w->SetLineWidth(2);
  mubg_w->GetXaxis()->CenterTitle(true);
  mubg_w->GetYaxis()->CenterTitle(true);
  mubg_w->Draw("HIST");
  c->SaveAs("sattach_y04_bg_w_mupt.png");
  mubg_tt->SetLineColor(kCyan+2);
  mubg_tt->SetFillColor(kCyan+2);
  mubg_tt->SetLineWidth(2);
  mubg_tt->GetXaxis()->CenterTitle(true);
  mubg_tt->GetYaxis()->CenterTitle(true);
  mubg_tt->Draw("HIST");
  c->SaveAs("sattach_y04_bg_tt_mupt.png");
  etach->Draw("HIST");
  c->SaveAs("sattach_y04_ch_mueta.png");
  etabg->SetLineColor(kCyan+3);
  etabg->SetFillColor(kCyan+3);
  etabg->SetLineWidth(2);
  etabg->GetXaxis()->CenterTitle(true);
  etabg->GetYaxis()->CenterTitle(true);
  etabg->Draw("HIST");
  c->SaveAs("sattach_y04_bg_mueta.png");
  etabg_w->SetLineColor(kCyan+2);
  etabg_w->SetFillColor(kCyan+2);
  etabg_w->SetLineWidth(2);
  etabg_w->GetXaxis()->CenterTitle(true);
  etabg_w->GetYaxis()->CenterTitle(true);
  etabg_w->Draw("HIST");
  c->SaveAs("sattach_y04_bg_w_mueta.png");
  etabg_tt->SetLineColor(kCyan+2);
  etabg_tt->SetFillColor(kCyan+2);
  etabg_tt->SetLineWidth(2);
  etabg_tt->GetXaxis()->CenterTitle(true);
  etabg_tt->GetYaxis()->CenterTitle(true);
  etabg_tt->Draw("HIST");
  c->SaveAs("sattach_y04_bg_tt_mueta.png");
  hbg_1->Draw("HIST");
  c->SaveAs("sattach_y04_d1_bg_jetht.png");
  hch_1->Draw("HIST");
  c->SaveAs("sattach_y04_d1_ch_jetht.png");
  htotal_1->Draw("HIST");
  c->SaveAs("sattach_y04_d1_total_jetht.png");
  hbg_2->Draw("HIST");
  c->SaveAs("sattach_y04_d2_bg_jetht.png");
  hch_2->Draw("HIST");
  c->SaveAs("sattach_y04_d2_ch_jetht.png");
  htotal_2->Draw("HIST");
  c->SaveAs("sattach_y04_d2_total_jetht.png");
  hbg_3->Draw("HIST");
  c->SaveAs("sattach_y04_d3_bg_jetht.png");
  hch_3->Draw("HIST");
  c->SaveAs("sattach_y04_d3_ch_jetht.png");
  htotal_3->Draw("HIST");
  c->SaveAs("sattach_y04_d3_total_jetht.png");
  hbg_4->Draw("HIST");
  c->SaveAs("sattach_y04_d4_bg_jetht.png");
  hch_4->Draw("HIST");
  c->SaveAs("sattach_y04_d4_ch_jetht.png");
  htotal_4->Draw("HIST");
  c->SaveAs("sattach_y04_d4_total_jetht.png");
  hbg_5->Draw("HIST");
  c->SaveAs("sattach_y04_d5_bg_jetht.png");
  hch_5->Draw("HIST");
  c->SaveAs("sattach_y04_d5_ch_jetht.png");
  htotal_5->Draw("HIST");
  c->SaveAs("sattach_y04_d5_total_jetht.png");
}
